### ISSUE TITLE
InfiniteScroll not defined

### ISSUE THREAD

**Issue by cleercode** [guillaumervls/react-infinite-scroll#11]
I'm getting this error:

```
Uncaught TypeError: Cannot read property '_defaultLoader' of undefined
React.addons.InfiniteScroll.React.createClass.getDefaultProps
```

Looks like `InfiniteScroll` isn't defined when it's used for `InfiniteScroll._defaultLoader`  in `getDefaultProps` (https://github.com/guillaumervls/react-infinite-scroll/commit/fad375982e1b95e7f84883d5765d13bae8be6537)

Any ideas? I feel like I had this working fine before... Maybe something with `React.createClass` changed?

**Comment by zachcowell** [comment]
I am experiencing the same issue. React v0.12.2
