### ISSUE TITLE
Don't fire again until success on previous request

### ISSUE THREAD

**Issue by braco** [guillaumervls/react-infinite-scroll#14]
This should probably not just keep firing when content is delayed from loading/rendering as is the case with any network calls.

Should we watch for SUCCESS events and block until then?

**Comment by flocks** [comment]
I had the same issue, it's not perfect but I've implemented a `delay` property you can pass to your component. It will wait before re-attaching the scroll handler and triggering the next loadMore call. 

https://github.com/flocks/react-infinite-scroll

```
<InfiniteScroll
   delay={1500}
   hasMore={this.props.hasmore}
   loadMore={this.getNextPage}
   pageStart={1}
>
```
`delay` is in milliseconds.
