### ISSUE TITLE
Doesn't work with react 0.13.2

### ISSUE THREAD

**Issue by StanOstapenko** [guillaumervls/react-infinite-scroll#20]
Cannot read property '_defaultLoader' of undefined
Cannot read property '__reactAutoBindMap' of undefined

**Comment by Wildhoney** [comment]
Works for me using `0.13.3` so I'm going to assume it also works for `0.13.2`:

```javascript
import IScroll from 'react-infinite-scroll';
const InfiniteScroll = IScroll(React);
```

And then use as normal in your JSX:

```html
<InfiniteScroll />
```
