### ISSUE TITLE
React.DOM is deprecated

### ISSUE THREAD

**Issue by msfeldstein** [guillaumervls/react-infinite-scroll#34]
Need to update to use ReactDOM package instead to clear out warnings.

<img width="633" alt="screen shot 2016-01-28 at 11 10 07 am" src="https://cloud.githubusercontent.com/assets/161135/12655842/c180fae8-c5af-11e5-90c5-292bc67204a8.png">

**Comment by thomasmodeneis** [comment]
+1

**Comment by danbovey** [comment]
Use this active fork with updated dependencies https://github.com/CassetteRocks/react-infinite-scroller
