### ISSUE TITLE
example is broken on jsfiddle.

### ISSUE THREAD

**Issue by export-mike** [guillaumervls/react-infinite-scroll#35]
http://jsfiddle.net/mb9vJ/2

**Comment by rankun203** [comment]
Yes, had the same issue.

**Comment by danbovey** [comment]
Demo here: http://cassetterocks.github.io/react-infinite-scroller/demo/

Source code here: https://github.com/CassetteRocks/react-infinite-scroller/blob/gh-pages/src/index.js

**Comment by Ouadie** [comment]
Same issue too

**Comment by danbovey** [comment]
@Ouadie The creator of this component isn't maintaining it, so the jsfiddle is likely to stay broken. Hopefully people find this [fork](https://github.com/CassetteRocks/react-infinite-scroller]) I created in all the issues and PRs I've been commenting on here 

Again, there's a demo above and you can use the source code to make a start with the all new and improved `react-infinite-scroller`  :smiley:.

**Comment by Ouadie** [comment]
Thanks! 
PS: Your fork url is broken ;)

**Comment by danbovey** [comment]
Sorry, fixed but there was also link from the demo site. And the source code for it is linked above in my first comment or on the `gh-pages` branch of the fork ^^ 😬
