### ISSUE TITLE
Giving ownership of this repo to someone that will maintain the project

### ISSUE THREAD

**Issue by zabojad** [guillaumervls/react-infinite-scroll#38]
It seems this repo is not being maintained anymore...

@guillaumervls what about giving ownership of this repo to someone that will maintain it?

Who would be interested in this? @danbovey would you?

**Comment by danbovey** [comment]
Yeah of course, I've tried to post links to the fork I'm running everywhere I can.

**Comment by axelson** [comment]
@danbovey are you talking about this fork?

https://github.com/CassetteRocks/react-infinite-scroller

**Comment by danbovey** [comment]
@axelson yep 😃
