### ISSUE TITLE
Keeps firing scrollListener

### ISSUE THREAD

**Issue by nidhi-ag** [guillaumervls/react-infinite-scroll#40]
In attachScrollListener why do we fire scrollListener(), it causes  load more without even any scroll or resize event happening ?

**Comment by danbovey** [comment]
This package is no longer being maintained, so if you're using a newer version of React, like 15.x you need to be using the fork I'm running at https://github.com/CassetteRocks/react-infinite-scroller.

On mount, we attach the scroll listener and also call it manually. This is to load the first set of items. You could disable it by setting `pageStart` to `-1` and then checking whether the `pageToLoad` parameter of your `loadMore` function is greater than 0.

**Comment by nidhi-ag** [comment]
Once scrollListener is being called for the first time...i handle load more with the >0 condition but it calls detachScrollListener as well, after that it is never attaching the event again.

**Comment by danbovey** [comment]
We detach the scroll listener because it would send off infinite calls to `loadMore`. We attach it again when the component updates (with new items added).

**Comment by nidhi-ag** [comment]
But we add new items on load more.. in this case that would never be called..

**Comment by danbovey** [comment]
We detach the scroll listener AND make the one call that's needed to `loadMore`.

https://github.com/CassetteRocks/react-infinite-scroller/blob/master/src/react-infinite-scroll.js#L53

**Comment by nidhi-ag** [comment]
yeah but for the first call i have disabled the data fetch as u suggested, so there won't be any update in the component.
