### ISSUE TITLE
Does this plugin supports React 16.2?

### ISSUE THREAD

**Issue by Ashviniv** [guillaumervls/react-infinite-scroll#42]
I am trying to use this plugin in my react 16.2 project, but it is giving following error:
![screenshot from 2018-01-11 10 23 34](https://user-images.githubusercontent.com/13194826/34809207-99835828-f6b9-11e7-805e-ea49ac53121c.png)

Does it support React 16.2, if not are there any chances that it will support  React 16 in near future?

**Comment by danbovey** [comment]
You have installed `react-infinite-scroll`, which is the old package that is no longer maintained. The npm package you need to install is `react-infinite-scroller`, which supports React 14-16.
