### ISSUE TITLE
First load, requests twice.

### ISSUE THREAD

**Issue by jojo-tutor** [guillaumervls/react-infinite-scroll#43]
I've noticed in my project, that when a component/container will load at first, the infinite scroll will request twice.
You can also see this in the example: http://cassetterocks.github.io/react-infinite-scroller/demo/, notice the Network request.

**Comment by danbovey** [comment]
Can't reproduce this on the demo page.

Can you also open this issue on the actual repo (https://github.com/CassetteRocks/react-infinite-scroller) if you wish to discuss further?

Can you let me know which os, browser and version you are running?

Thanks!

**Comment by jojo-tutor** [comment]
Linux Mint 18.3, Google Chrome: Version 64.0.3282.119 (Official Build) (64-bit)
Please see screenshot below:
![react infinite scroller 1](https://user-images.githubusercontent.com/18729213/36952865-06f3c676-2050-11e8-9f1a-148f24bd4997.jpg)
