### ISSUE TITLE
loadmore twice

### ISSUE THREAD

**Issue by isaak-zmg** [guillaumervls/react-infinite-scroll#44]
Every time the loadmore event is triggered, it triggers two times

**Comment by isaak-zmg** [comment]
![image](https://user-images.githubusercontent.com/15681939/37285413-e9b6949a-2639-11e8-9edd-5d05fd8d3441.png)

![image](https://user-images.githubusercontent.com/15681939/37285441-fa615c58-2639-11e8-83a9-17c82bafa593.png)

**Comment by danbovey** [comment]
Copied your comments to the issue you opened on react-infinite-scroller.
