### ISSUE TITLE
Support for bower

### ISSUE THREAD

**Issue by chengyin** [guillaumervls/react-infinite-scroll#8]
I understand how react itself uses browserify, but we have a repo that uses other stack and we use bower to manage dependencies.

**Comment by barsukov** [comment]
+1

**Comment by djett41** [comment]
+1

**Comment by micmmakarov** [comment]
+1

**Comment by micmmakarov** [comment]
I use with bower+rails so bower is so much more convenient to track versions etc

**Comment by micmmakarov** [comment]
well, seems like it was stopped being maintained

**Comment by barsukov** [comment]
Probably , I was made my own small react infinite scroll mixin , which really super simple and stupid. Need only extract to bower component :)
